config/routes.rb
RailsPrelaunchSignup::Application.routes.draw do

  resources :activities

  resource :calendar, :only => [:show]

  resources :events

#----- Prelaunch sign up------------------------
  authenticated :user do
    root :to => 'home#index'
  end
    root :to => 'home#index'

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'units/unit_update' => 'units#unit_update', :via => :get, :as => :unit_update

#------------Baseapp2----------------

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

#------------Baseapp2------end----------
  resources   :after_register
#------------Dhtmlx grid----------------------
    resources :societies do
       match '/master',      :to => 'societies#view',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resource :unit_types do
       match '/unit_types',  :to => 'unit_types#show',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resources :members do
       match '/view_members',     :to => 'members#view',  :requirements => { :method => :get }
        collection do
          get 'data'
          get 'dbaction'
          get 'view'
          get 'index'
       end
    end

    resources :memberships do
      match '/memberships', :to => 'memberships#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
     end

   resources :units do
    match '/unit', :to => 'units#show', :requirements => { :method => :get }
      collection do
        get 'data'
        get 'dbaction'
        get 'show'
        get 'index'
      end
    end
            
     resources :bill_setups do
      match '/bill_setups',       :to => 'bill_setups#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
      end
     resources :bill_headers do
      match '/bill_headers',       :to => 'bill_headers#view',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
          end
      end

     resources :bills do
      match '/view_bills',       :to => 'bills#view',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'view'
            get 'index'
          end
      end
     resources :vendors do
      match '/view_vendors',       :to => 'vendors#show',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'show'
            get 'index'
          end
      end
  
  resources :staffs
  resources :meetings 
  resources :meeting_types 

  match '/committee_members',  :to => 'committee_members#index'
  match '/staffs',      :to => 'staffs#index'
  match '/vendors',     :to => 'vendors#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action
  # tublar--------------------

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  match '/videos', :to =>  "videos#index"
#  get "/insert_search/:search_type/:search"     => "api#search"
#  get "/:username/playlist/:playlist_name.json" => "api#user_playlist"
#  get "/stats"                                => "stats#index"
#  get "/genres"                               => "videos#genres"
#  get "/genre/:artist_band"                   => "videos#index"
#  get "/just/:artist_band"                    => "videos#index"
#  get "/similar/:artist_band"                 => "videos#index"
#  get "/video/:video_id"                      => "videos#index"
  
#  get "/:username/playlists"                  => "playlists#index"
#  get "/:username/playlist/:playlist_name"    => "playlists#listen"
#  match "/playlist/create"                    => "playlists#create"
#  match "/playlist/add_video"                 => "playlists#add_video"
#  match "/playlist/delete_video"              => "playlists#delete_video"
#  match "/get_playlists_video_belongs_to"     => "playlists#get_playlists_video_belongs_to"
  
#  post "/check_banned"                        => "bannedVideos#check"
#  post "/ban_video"                           => "bannedVideos#ban_video"

  get "static_pages/help"
#  get "static_pages/about"
#  get "static_pages/contact"
  match '/help',    :to => 'static_pages#help'
#  match '/about',   :to => 'static_pages#about'
#  match '/contact', :to => 'static_pages#contact'


  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :active, :gender, :joining_date, :society_id, :staff_age, 
  :staff_category, :staff_current_address, :staff_email, :staff_name, 
  :staff_permamnent_address, :staff_phone, :staff_salary, :avatar

  belongs_to :society
#---------paperclip----------------------------------
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>" }
#  validates_attachment :avatar, :presence => true
#  validates_attachment_size :avatar, :size => [< 1000], :message => "has to be in 1000kb size"
  validates_attachment_content_type :avatar, :content_type => ['image/jpg', 'image/pjpeg', 'image/jpeg', 'image/png'], :message => "has to be in jpg/jpeg/png/gif format"

#---------paperclip end-------------------------------
  protected
  
  def set_orientation
    original_image = self.image.to_file(:original)
    dimensions = Paperclip::Geometry.from_file(original_file)
    self.orientation = (dimensions.width > dimensions.height) ? 'landscape' : 'portrait'
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # GET /staffs
  # GET /staffs.json
  before_filter :authenticate_user!
  load_and_authorize_resource 

  def index
    if current_user.has_role? :super_admin
      @staffs = Staff.order(:staff_name).paginate :page => params[:page], :per_page => 10
      @staff  = Staff.find(params[:staff_id]) if params[:staff_id]
    else
      @staffs = Staff.where("society_id = ?", current_user.society_id).order(:staff_name).paginate :page => params[:page], :per_page => 10      
      @staff  = Staff.where("society_id = ?", current_user.society_id).find(params[:staff_id]) if params[:staff_id]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staffs }
    end
  end


  # GET /staffs/1
  # GET /staffs/1.json
  def show
    if current_user.has_role? :super_admin
      @staff = Staff.find(params[:id])
    else
      @staff = Staff.where("society_id = ?", current_user.society_id).find(params[:id])
    end
      if @staff.blank?
        redirect_to staffs_url, :notice => "You don't have access to staff with this ID"
      else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @staff }
      end
    end
  end


  # GET /staffs/new
  # GET /staffs/new.json
  def new
    @staff = Staff.new
#    :society_id => current_user.society_id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/1/edit
  def edit
    @staff = Staff.find(params[:id])
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(params[:staff])
    @staff.society_id = current_user.society_id

    respond_to do |format|
      if @staff.save
      track_activity @staff
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render json: @staff, status: :created, location: @staff }
      else
        format.html { render action: "new" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /staffs/1
  # PUT /staffs/1.json
  def update
    @staff = Staff.find(params[:id])

    respond_to do |format|
      if @staff.update_attributes(params[:staff])
      track_activity @staff
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
      track_activity @staff

    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb">
    <li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
    <li><a href="http://localhost:3000/staffs">Staff</a> <span class="divider">/</span></li>                                      
	<li class="active"><%= controller.action_name.capitalize %> </li>
	<li class="pull-right"> 
	</li>
    </ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span7">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"><%= @staff.staff_name %> </h2>
			<div class="block box_content round_bottom padding_20">

<%= form_for @staff, :html => { :multipart => true } do |f| %>
				<% if @staff.errors.any? %>
					<div class="error_messages">
						<h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>
						<ul>
						<% @staff.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
						</ul>
					</div>
				<% end %>
				<div class="well form-inline">
					<%= f.text_field :staff_name, :style=>"width:40%;", :placeholder => 'Name of staff' %>
					<%= f.text_field :gender, :style=>"width:10%;", :placeholder => 'Gender' %>
					<%= f.text_field :staff_age, :style=>"width:10%;", :placeholder => 'Age' %>
				</div>
				<div class="well form-inline">
					<%= f.text_field :staff_category, :style=>"width:25%;", :placeholder => 'Designation' %> 
					<%= f.number_field :staff_salary, :style=>"width:15%;", :placeholder => 'Salary' %> 
					<%= f.text_field :joining_date, :style=>"width:25%;", :placeholder => 'Joining Date' %> 
				</div>
			 	<div class="well form-inline">
					<%= f.text_field :staff_email, :style=>"width:40%;", :placeholder => 'Email' %> 
					<%= f.text_field :staff_phone, :style=>"width:40%;", :placeholder => 'Mobile' %> 
				</div>
				<div class="well form-inline">
					<%= f.text_field :staff_current_address, :style=>"width:45%;", :placeholder => 'Current Address' %> 
					<%= f.text_field :staff_permamnent_address, :style=>"width:45%;", :placeholder => 'Permanent Address' %> 
				</div>
			</div>
		</div>
	</div>
	
	<div class="span5">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"><%= controller.action_name.capitalize %> Photo</h2>
			<div class="block box_content round_bottom padding_20">

				<label class="control-label" for="focusedInput">Staff Photo</label>
				  <%= f.file_field :avatar %>
				<label class="control-label" for="focusedInput">Active</label>
				<div class="controls"><%= f.check_box :active %></div>
			 	<div class="form-actions">
					<%= f.submit nil, :class => 'btn btn-primary' %>
					<%= link_to 'Cancel', staffs_path, :class => 'btn' %>
				</div>
</form>	<% end %>
			</div>
		</div>
	</div>
</div>

app/views/staffs/index.html.erb
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>
			<li class="active">Staffs </li>
		</ul>
	</div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span9">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"></h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">
				<div class="block box_content round_bottom padding_20">
				<table class="table table-striped table-condensed table-bordered">
				<thead>
				  <tr>
					<th>Name</th>
					<th>Gender</th>
					<th>Age</th>
					<th>Phone</th>
					<th>Designation</th>
					<th>Salary</th>
					<th>Joining Date</th>
					<th>Is active</th>
					<th>
				  </tr>
				</thead>
				<tbody>
				<% content_for :staff_name, @staff ? @staff.staff_name : "staffs" %>
					<% for staff in @staffs %>
					<div class="event">
					<tr>
						<td><%= link_to staff.staff_name, :staff_id => staff %></td>
						<td><%= staff.gender %></td>
						<td><%= staff.staff_age %></td>
						<td><%= staff.staff_phone %></td>
						<td><%= staff.staff_category %></td>
						<td><%= staff.staff_salary %></td>
						<td><%= l(staff.joining_date, :format => :long) if staff.joining_date %></td>
						<td><%= staff.active %></td>
					</tr>
					</div>
					<% end %>
				</tbody>
				</table>
				<%= will_paginate @staffs %>
					<% if current_user.has_role? :super_admin or current_user.has_role? :society_manager %>
					<div class="form-actions">
						<%= link_to 'New Staff', new_staff_path , :class => 'btn' %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="span3">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"></h2>
			<div class="toggle_container">
				<div class="block box_content round_bottom ">
					<div data-pjax-container>
					<% if @staff %>
						<div id="event_details">
						<h3><%= best_in_place_if @staff.staff_name, @staff, :staff_name %></h3>
						<dl>
							<dt> <%= link_to (image_tag @staff.avatar.url(:medium)), @staff %></dt>
							<dt><%= best_in_place @staff,:staff_email, @staff %>
							<%= @staff.society_id %></dt>
						</dl>
						<% if current_user.has_role? :super_admin or current_user.has_role? :society_manager %>
						<div class="form-actions">
							<%= link_to ( image_tag("/assets/Overlay-edit.png")), edit_staff_path(@staff), :class => 'btn' %>
							<%= link_to ( image_tag("/assets/Overlay-cancel.png")), @staff, method: :delete, confirm: "Are you sure?", :class => 'btn' %>
						</div>
						<% end %>
					</div>
					<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--/row-->

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row-fluid">
  <div class="span12">
	<ul class="breadcrumb">
	<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>
	<li><a href="http://localhost:3000/staffs">Staffs</a> <span class="divider">/</span></li>
	<li class="active"><%= @staff.staff_name %>
	</ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span8">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"></h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">
				<div class="block box_content round_bottom padding_20">
				<p><b>Name:</b>
				  <%= @staff.staff_name %></p>
				<p><b>Gender:</b>
				  <%= @staff.gender %></p>
				<p><b>Age:</b>
				  <%= @staff.staff_age %></p>
				<p><b>Email:</b>
				  <%= @staff.staff_email %></p>
				<p><b>Phone:</b>
				  <%= @staff.staff_phone %></p>
				<p><b>Current address:</b>
				  <%= @staff.staff_current_address %></p>
				<p><b>Permamnent address:</b>
				  <%= @staff.staff_permamnent_address %></p>
				<p><b>Designation:</b>
				  <%= @staff.staff_category %></p>
				<p><b>Salary:</b>
				  <%= @staff.staff_salary %></p>
				<p><b>Joining date:</b>
				  <%= @staff.joining_date %></p>
				<%= link_to 'Edit', edit_staff_path(@staff) %>
				<%= link_to 'Back', staffs_path %>
				</div>
			</div>
		</div>
	</div>
	<div class="span4">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top">Staff</h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">
				<div class="block box_content round_bottom padding_20">
					<ul>
					<%= image_tag @staff.avatar.url %>
					<%= image_tag @staff.avatar.url(:medium) %>
					<%= image_tag @staff.avatar.url(:thumb) %>
				<p><b>Active:</b>
				  <%= @staff.active %></p>
				<p><b>Society:</b>
				  <%= @staff.society_id %></p>
					</ul>
				</div>
			</div>
		</div>
	</div>

</div><!--/row--> 

app/views/staffs/show1.html.erb

<p id="notice"><%= notice %></p>
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb">
    <li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
    <li><a href="http://localhost:3000/staffs">Staffs</a> <span class="divider">/</span></li>                                      
	<li class="active"><%= @staff.staff_name %>
    </ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span8">
        <div class="box grad_colour_dark_blue" id="box_0">
            <h2 class="box_head round_top"></h2>
            <a href="#" class="settings box_button_3" title="config">&nbsp;</a>
            <a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
            <a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
            <div class="toggle_container">					
                <div class="block box_content round_bottom padding_20">

				<p><b>Staff name:</b>
				  <%= @staff.staff_name %></p>
				<p><b>Gender:</b>
				  <%= @staff.gender %></p>
				<p><b>Staff category:</b>
				  <%= @staff.staff_category %></p>
				<p><b>Staff age:</b>
				  <%= @staff.staff_age %></p>
				<p><b>Staff email:</b>
				  <%= @staff.staff_email %></p>
				<p><b>Staff phone:</b>
				  <%= @staff.staff_phone %></p>
				<p><b>Staff current address:</b>
				  <%= @staff.staff_current_address %></p>
				<p><b>Staff permamnent address:</b>
				  <%= @staff.staff_permamnent_address %></p>
				<p><b>Active:</b>
				  <%= @staff.active %></p>
				<p><b>Joining date:</b>
				  <%= @staff.joining_date %></p>
				<p><b>Staff salary:</b>
				  <%= @staff.staff_salary %></p>
					<%= image_tag @staff.avatar.url %>
					<%= image_tag @staff.avatar.url(:medium) %>
					<%= image_tag @staff.avatar.url(:thumb) %>
				<p><b>Society:</b>
				  <%= @staff.society_id %></p>
				<%= link_to 'Edit', edit_staff_path(@staff) %>
				<%= link_to 'Back', staffs_path %>
                </div>                                
            </div>
        </div>
	</div>
	<div class="span4">
        <div class="box grad_colour_dark_blue" id="box_0">
            <h2 class="box_head round_top">Staff</h2>
            <a href="#" class="settings box_button_3" title="config">&nbsp;</a>
            <a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
            <a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
            <div class="toggle_container">					
                <div class="block box_content round_bottom padding_20">
					<ul>
					</ul>
                </div>                                
            </div>
        </div>
	</div>

</div><!--/row--> 