config/routes.rb
RailsPrelaunchSignup::Application.routes.draw do

  resources :activities

  resource :calendar, :only => [:show]

  resources :events

#----- Prelaunch sign up------------------------
  authenticated :user do
    root :to => 'home#index'
  end
    root :to => 'home#index'

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'units/unit_update' => 'units#unit_update', :via => :get, :as => :unit_update

#------------Baseapp2----------------

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

#------------Baseapp2------end----------
  resources   :after_register
#------------Dhtmlx grid----------------------
    resources :societies do
       match '/master',      :to => 'societies#view',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resource :unit_types do
       match '/unit_types',  :to => 'unit_types#show',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resources :members do
       match '/view_members',     :to => 'members#view',  :requirements => { :method => :get }
        collection do
          get 'data'
          get 'dbaction'
          get 'view'
          get 'index'
       end
    end

    resources :memberships do
      match '/memberships', :to => 'memberships#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
     end

   resources :units do
    match '/unit', :to => 'units#show', :requirements => { :method => :get }
      collection do
        get 'data'
        get 'dbaction'
        get 'show'
        get 'index'
      end
    end
            
     resources :bill_setups do
      match '/bill_setups',       :to => 'bill_setups#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
      end
     resources :bill_headers do
      match '/bill_headers',       :to => 'bill_headers#view',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
          end
      end

     resources :bills do
      match '/view_bills',       :to => 'bills#view',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'view'
            get 'index'
          end
      end
     resources :vendors do
      match '/view_vendors',       :to => 'vendors#show',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'show'
            get 'index'
          end
      end
  
  resources :staffs
  resources :meetings 
  resources :meeting_types 

  match '/committee_members',  :to => 'committee_members#index'
  match '/staffs',      :to => 'staffs#index'
  match '/vendors',     :to => 'vendors#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action
  # tublar--------------------

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  match '/videos', :to =>  "videos#index"
#  get "/insert_search/:search_type/:search"     => "api#search"
#  get "/:username/playlist/:playlist_name.json" => "api#user_playlist"
#  get "/stats"                                => "stats#index"
#  get "/genres"                               => "videos#genres"
#  get "/genre/:artist_band"                   => "videos#index"
#  get "/just/:artist_band"                    => "videos#index"
#  get "/similar/:artist_band"                 => "videos#index"
#  get "/video/:video_id"                      => "videos#index"
  
#  get "/:username/playlists"                  => "playlists#index"
#  get "/:username/playlist/:playlist_name"    => "playlists#listen"
#  match "/playlist/create"                    => "playlists#create"
#  match "/playlist/add_video"                 => "playlists#add_video"
#  match "/playlist/delete_video"              => "playlists#delete_video"
#  match "/get_playlists_video_belongs_to"     => "playlists#get_playlists_video_belongs_to"
  
#  post "/check_banned"                        => "bannedVideos#check"
#  post "/ban_video"                           => "bannedVideos#ban_video"

  get "static_pages/help"
#  get "static_pages/about"
#  get "static_pages/contact"
  match '/help',    :to => 'static_pages#help'
#  match '/about',   :to => 'static_pages#about'
#  match '/contact', :to => 'static_pages#contact'


  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  
  attr_accessible  :meeting_type_id, :meeting_datetime, :meeting_place, :issued_by, :issue_date,
  :society_id, :agendas_attributes, :meeting_name, :invited_tokens, :attended_tokens
  
  has_many :agendas
  belongs_to :meeting_type
  
  belongs_to :society

  validates :meeting_datetime, :presence => true
  validates :issue_date, :presence => true
#  validates :meeting_place, :presence => true
  validates :meeting_type_id, :presence => true

  default_scope :order => 'meeting_datetime DESC'

  accepts_nested_attributes_for :agendas, allow_destroy: true
#--------token-input------------------
  def meeting_name
    meeting_type.try(:name)
  end
  
  def meeting_name=(name)
    self.meeting_type = MeetingType.find_or_create_by_name(name) if name.present?
  end

  has_many :meeting_invited_members
  has_many :meeting_attended_members
  has_many :members, through: :meeting_invited_members
  has_many :members, through: :meeting_attended_members
  attr_reader :invited_tokens
  attr_reader :attended_tokens
  
  def invited_tokens=(tokens)
    self.member_ids = Member.ids_from_tokens(tokens)
  end
  def attended_tokens=(tokens)
    self.member_ids = Member.ids_from_tokens(tokens)
  end

#  before_create :set_issue_date_to_now

#  def formatted_meeting_datetime
#  meeting_datetime.strftime('%d/%m/%Y %H:%M')
#  end
#  def formatted_meeting_datetime=(time_str)
#    self.meeting_datetime = Time.parse(time_str)
#  end

#----------end------------------------
end

app/models/meeting_type.rb
class MeetingType < ActiveRecord::Base
  attr_accessible :name
  has_many :meetings
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  respond_to :html, :json
  before_filter :authenticate_user!
  load_and_authorize_resource 

  def index
    if current_user.has_role? :super_admin
      @meetings = Meeting.order("meeting_datetime DESC").paginate :page => params[:page], :per_page => 10
      @meeting = Meeting.find(params[:meeting_id]) if params[:meeting_id]
    else
      @meetings = Meeting.order("meeting_datetime DESC").where("society_id = ?", current_user.society_id).paginate :page => params[:page], :per_page => 10     
      @meeting = Meeting.where("society_id = ?", current_user.society_id).find(params[:meeting_id]) if params[:meeting_id]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end


  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new
    @meeting.issue_date = Time.now.to_formatted_s(:short)
    @meeting.meeting_datetime = 4.days.from_now.to_formatted_s(:short)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])
    @meeting.society_id = current_user.society_id
    respond_to do |format|
      if @meeting.save
      track_activity @meeting
        format.html { redirect_to @meeting, only_path: true , notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])
    @meeting.society_id = current_user.society_id

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
      track_activity @meeting
        format.html { redirect_to(@meeting, only_path: true , :notice => 'Meeting was successfully updated.') }
        format.json { respond_with_bip(@meeting) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@meeting) }
      end
    end
  end
  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
      track_activity @meeting

    respond_to do |format|
      format.html { redirect_to meetings_url, only_path: true  }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_agenda_fields.html.erb
<fieldset>
  <%= f.label :meeting_agendas, "Agenda" %>
  <%= f.text_area :meeting_agendas %>
      <div class="controls">
        <label class="checkbox uniform">
		  <%= f.check_box :_destroy %>
		  <%= f.label :_destroy, "Remove Agenda" %>
        </label>
      </div>
  <%= f.fields_for :resolutions do |builder| %>
    <%= render 'resolution_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Resolution", f, :resolutions %>
</fieldset>

app/views/meetings/_agenda_fields.html.haml
%fieldset
  = f.label :meeting_agendas, "Agenda"
  = f.text_area :meeting_agendas
  .controls
    %label.checkbox.uniform
      = f.check_box :_destroy
      = f.label :_destroy, "Remove Agenda"
  = f.fields_for :resolutions do |builder|
    = render 'resolution_fields', f: builder
  = link_to_add_fields "Add Resolution", f, :resolutions

app/views/meetings/_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb">
    <li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
    <li><a href="http://localhost:3000/meetings">Meetings</a> <span class="divider">/</span></li>                                      
	<li class="active"><%= controller.action_name.capitalize %> </li>
	<li class="pull-right"> 
	</li>
    </ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span6">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"><%= @meeting.meeting_name %> meeting Agenda/Resolution</h2>
			<div class="block box_content round_bottom padding_20">
	<%= form_for @meeting, :html => { :class => 'form-horizontal' }, :validate => false do |f| %>
				<%= f.error_messages %>
				<fieldset>
					<%= f.fields_for :agendas do |builder| %>
						<%= render 'agenda_fields', f: builder %>
					<% end %>
					<h4><%= link_to_add_fields "Add Agenda", f, :agendas %></h4>
				</fieldset>
			</div>
		</div>
	</div>
	<div class="span6">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"><%= controller.action_name.capitalize %> meeting details</h2>
			<div class="block box_content round_bottom padding_20">
				<label class="control-label" for="focusedInput">Meeting Type</label>
				<div class="controls"><%= f.text_field :meeting_name, data: {autocomplete_source: MeetingType.order(:name).map(&:name)} %></div>
				<label class="control-label" for="focusedInput">Meeting Called by</label>
				<div class="controls"><%= f.text_field :issued_by %></div>
				<label class="control-label" for="focusedInput">Meeting Place</label>
				<div class="controls"><%= f.text_field :meeting_place %></div>
				<label class="control-label" for="focusedInput">Meeting issue date</label>
				<div class="controls"><%= f.text_field :issue_date %></div>
				<label class="control-label" for="focusedInput">Meeting Date & Time</label>
				<div class="controls"><%= f.text_field :meeting_datetime %></div>
				<label class="control-label" for="focusedInput">Invited Members</label>
				<div class="controls"><%= f.text_field :invited_tokens, data: {load: @meeting.members} %></div>
<% if ['issue_date.to_date = ?', Date.today] %>
				<label class="control-label" for="focusedInput">Attending Members</label>
				<div class="controls"><%= f.text_field :attended_tokens, data: {load: @meeting.members} %></div>
<% end %>
			 	<div class="form-actions">
					<%= f.submit nil, :class => 'btn btn-primary' %>
					<%= link_to 'Cancel', meetings_path, :class => 'btn' %>
				</div>
	<% end %></form>
			</div>
		</div>
	</div>
</div><!--/row-->

app/views/meetings/_resolution_fields.html.erb
<fieldset>
  <ul><%= f.label :meeting_resolutions, "Resolution" %>
  <%= f.text_area :meeting_resolutions %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %></ul>
</fieldset>

app/views/meetings/edit.html.erb
<%= render "form" %>

app/views/meetings/index.html.erb
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>
			<li class="active">Meetings </li>
		</ul>
	</div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span6">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"></h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">					
				<div class="block box_content round_bottom padding_20">
				<table class="table table-striped table-condensed ">
					<tbody>
						<% content_for :meeting_name, @meeting ? @meeting.meeting_name : "meetings" %>
						<% for meeting in @meetings %>
						<div class="event">
							<tr>
							<td><%= link_to meeting.meeting_name, :meeting_id => meeting %>
								on <%= l(meeting.meeting_datetime, :format => :long) %>&nbsp;&nbsp;</td>
							<td><%= meeting.society_id %></td>
							</tr>
						</div>
						<% end %>
					</tbody>
				</table>
						<%= will_paginate @meetings %>
						<% if current_user.has_role? :super_admin or current_user.has_role? :society_meeting %>
						<div class="form-actions">
							<%= link_to 'New Meeting', new_meeting_path , :class => 'btn' %>
						</div>
						<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="span6">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"></h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">					
				<div class="block box_content round_bottom padding_20">
					<div data-pjax-container>
						<% if @meeting %>
						<div id="event_details">
						<h3><%= best_in_place_if @meeting.meeting_name, @meeting, :meeting_name %></h3>
						<dl>
						<dt> Circular Date:
							&nbsp;&nbsp;&nbsp;<%= l(@meeting.issue_date, :format => :long) %></dt>
						<dt>Meeting Place:
							&nbsp;<%= best_in_place_if @meeting.meeting_place, @meeting, :meeting_place %></dt>
						<dt>Called by:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<%= meeting.issued_by %></dt>
						<dt>Agenda:</dt>
						<% @meeting.agendas.each do |agenda| %>
							<li> <%= agenda.meeting_agendas %></li>
							<ol class="resolutions">
								<% agenda.resolutions.each do |resolution| %>
								<li><%= resolution.meeting_resolutions %></li>
								<% end %>
							</ol>
							</li>
						<% end %>
						</dl>
						<% if current_user.has_role? :super_admin or current_user.has_role? :society_meeting %>
						<div class="form-actions">
							<%= link_to ( image_tag("/assets/Overlay-edit.png")), edit_meeting_path(@meeting), :class => 'btn' %>
							<%= link_to ( image_tag("/assets/Overlay-cancel.png")), @meeting, method: :delete, confirm: "Are you sure?", :class => 'btn' %>
						</div>
						<% end %>
					</div>
					<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--/row-->

app/views/meetings/new.html.erb
<%= render "form" %>

app/views/meetings/show.html.erb
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
			<li><a href="http://localhost:3000/meetings">Meetings</a> <span class="divider">/</span></li>                                      
			<li class="active"><%= @meeting.meeting_name %>
		</ul>
	</div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span8">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top">Agenda for the meeting on <%= l(@meeting.meeting_datetime, :format => :long) %>&nbsp;
			at <%= @meeting.meeting_place %></h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">					
				<div class="block box_content round_bottom padding_20">
					<ol class="agendas">
						<% @meeting.agendas.each do |agenda| %>
						  <li> <%= agenda.meeting_agendas %>
						    <ol class="resolutions">
						      <% agenda.resolutions.each do |resolution| %>
						        <li><%= resolution.meeting_resolutions %></li>
						      <% end %>
						    </ol>
						  </li>
						<% end %>
					</ol>
				<div class="form-actions">
				<% if current_user.has_role? :super_admin or current_user.has_role? :society_meeting %>
					<%= link_to 'Edit', edit_meeting_path(@meeting), :class => 'btn' %>
				<% end %>
					<%= link_to 'Back to Meetings', meetings_path, :class => 'btn' %>
				</div>
				</div>
			</div>
		</div>
	</div>
	<div class="span4">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top">Attending Members</h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">					
				<div class="block box_content round_bottom padding_20">
					<ul>
					<% @meeting.members.each do |member| %>
					  <li><%= member.name %></li>
					<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div><!--/row--> 