config/routes.rb
RailsPrelaunchSignup::Application.routes.draw do

  resources :activities

  resource :calendar, :only => [:show]

  resources :events

#----- Prelaunch sign up------------------------
  authenticated :user do
    root :to => 'home#index'
  end
    root :to => 'home#index'

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'units/unit_update' => 'units#unit_update', :via => :get, :as => :unit_update

#------------Baseapp2----------------

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

#------------Baseapp2------end----------
  resources   :after_register
#------------Dhtmlx grid----------------------
    resources :societies do
       match '/master',      :to => 'societies#view',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resource :unit_types do
       match '/unit_types',  :to => 'unit_types#show',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resources :members do
       match '/view_members',     :to => 'members#view',  :requirements => { :method => :get }
        collection do
          get 'data'
          get 'dbaction'
          get 'view'
          get 'index'
       end
    end

    resources :memberships do
      match '/memberships', :to => 'memberships#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
     end

   resources :units do
    match '/unit', :to => 'units#show', :requirements => { :method => :get }
      collection do
        get 'data'
        get 'dbaction'
        get 'show'
        get 'index'
      end
    end
            
     resources :bill_setups do
      match '/bill_setups',       :to => 'bill_setups#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
      end
     resources :bill_headers do
      match '/bill_headers',       :to => 'bill_headers#view',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
          end
      end

     resources :bills do
      match '/view_bills',       :to => 'bills#view',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'view'
            get 'index'
          end
      end
     resources :vendors do
      match '/view_vendors',       :to => 'vendors#show',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'show'
            get 'index'
          end
      end
  
  resources :staffs
  resources :meetings 
  resources :meeting_types 

  match '/committee_members',  :to => 'committee_members#index'
  match '/staffs',      :to => 'staffs#index'
  match '/vendors',     :to => 'vendors#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action
  # tublar--------------------

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  match '/videos', :to =>  "videos#index"
#  get "/insert_search/:search_type/:search"     => "api#search"
#  get "/:username/playlist/:playlist_name.json" => "api#user_playlist"
#  get "/stats"                                => "stats#index"
#  get "/genres"                               => "videos#genres"
#  get "/genre/:artist_band"                   => "videos#index"
#  get "/just/:artist_band"                    => "videos#index"
#  get "/similar/:artist_band"                 => "videos#index"
#  get "/video/:video_id"                      => "videos#index"
  
#  get "/:username/playlists"                  => "playlists#index"
#  get "/:username/playlist/:playlist_name"    => "playlists#listen"
#  match "/playlist/create"                    => "playlists#create"
#  match "/playlist/add_video"                 => "playlists#add_video"
#  match "/playlist/delete_video"              => "playlists#delete_video"
#  match "/get_playlists_video_belongs_to"     => "playlists#get_playlists_video_belongs_to"
  
#  post "/check_banned"                        => "bannedVideos#check"
#  post "/ban_video"                           => "bannedVideos#ban_video"

  get "static_pages/help"
#  get "static_pages/about"
#  get "static_pages/contact"
  match '/help',    :to => 'static_pages#help'
#  match '/about',   :to => 'static_pages#about'
#  match '/contact', :to => 'static_pages#contact'


  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

end

app/models/bill_header.rb
class BillHeader < ActiveRecord::Base
  attr_accessible :bill_cycle, :bill_date, :bill_number_end, :bill_number_format, :bill_number_start, 
  :from_date, :grace_period, :locked_period, :society_id, :to_date

  belongs_to :society
         
 scope :billheader_search, lambda { |search| 
  search = "%#{search}%"
  where('bill_number_start LIKE ? ',  search)
 }

end

app/controllers/bill_headers_controller.rb
class BillHeadersController < ApplicationController
  # GET /bill_headers
  # GET /bill_headers.json
  respond_to :html, :json
  before_filter :authenticate_user!
  load_and_authorize_resource 

  def index
    if current_user.has_role? :super_admin
      @bill_headers = BillHeader.order("id").paginate :page => params[:page], :per_page => 10
      @bill_header = BillHeader.find(params[:bill_header_id]) if params[:bill_header_id]

    else
      @bill_headers = BillHeader.order("id").where("society_id = ?", current_user.society_id).paginate :page => params[:page], :per_page => 10     
      @bill_header = BillHeader.where("society_id = ?", current_user.society_id).find(params[:bill_header_id]) if params[:bill_header_id]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bill_headers }
    end
  end

  # GET /bill_headers/1
  # GET /bill_headers/1.json
  def show
    @bill_header = BillHeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill_header }
    end
  end

  # GET /bill_headers/new
  # GET /bill_headers/new.json
  def new
    @bill_header = BillHeader.new
#    @meeting.issue_date = Time.now.to_formatted_s(:short)
#    @meeting.meeting_date = 4.days.from_now.to_formatted_s(:short)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill_header }
    end
  end

  # GET /bill_headers/1/edit
  def edit
    @bill_header = BillHeader.find(params[:id])
  end

  # POST /bill_headers
  # POST /bill_headers.json
  def create
    @bill_header = BillHeader.new(params[:bill_header])
    @bill_header.society_id = current_user.society_id

    respond_to do |format|
      if @bill_header.save
      track_activity @bill_header
        format.html { redirect_to @bill_header, only_path: true, notice: 'Bill header was successfully created.' }
        format.json { render json: @bill_header, status: :created, location: @bill_header }
      else
        format.html { render action: "new" }
        format.json { render json: @bill_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bill_headers/1
  # PUT /bill_headers/1.json
  def update
    @bill_header = BillHeader.find(params[:id])

    respond_to do |format|
      if @bill_header.update_attributes(params[:bill_header])
      track_activity @bill_header
        format.html { redirect_to @bill_header, only_path: true, notice: 'Bill header was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_headers/1
  # DELETE /bill_headers/1.json
  def destroy
    @bill_header = BillHeader.find(params[:id])
    @bill_header.destroy
    track_activity @bill_header

    respond_to do |format|
      format.html { redirect_to bill_headers_url, only_path: true }
      format.json { head :no_content }
    end
  end
end

app/helpers/bill_headers_helper.rb
module BillHeadersHelper
end

app/views/bill_headers/_form.html.erb
<%= form_for(@bill_header) do |f| %>
	<% if @bill_header.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@bill_header.errors.count, "error") %> prohibited this bill header from being saved:</h2>
		<ul>
			<% @bill_header.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>
			<li><a href="http://localhost:3000/bill_headers">Bill Headers</a> <span class="divider">/</span></li>
			<li class="active"><%= controller.action_name.capitalize %> </li>
			<li class="pull-right"> </li>
		</ul>
	</div><!--/span-->
</div><!--/row-->
<div class="row-fluid">
	<div class="span6">
		<div class="box grad_colour_dark_blue">
			<h2 class="box_head round_top">Bill Header</h2>
			<div class="toggle_container">
				<div class="block box_content round_bottom padding_20">
					<label class="control-label" for="focusedInput">Bill Date</label>
					<div class="controls"><%= f.text_field :bill_date %></div>
					<label class="control-label" for="focusedInput">From</label>
					<div class="controls"><%= f.text_field :from_date %></div>
					<label class="control-label" for="focusedInput">To</label>
					<div class="controls"><%= f.text_field :to_date %></div>
					<label class="control-label" for="focusedInput">Bill Cycle (2 for bi-monthly)</label>
					<div class="controls"><%= f.text_field :bill_cycle %></div>
					<label class="control-label" for="focusedInput">Grace Period (number of Days)</label>
					<div class="controls"><%= f.number_field :grace_period %></div>
				</div>
			</div>
		</div>
	</div><!--/span-->
	<div class="span6">
		<div class="box">
		<h2 class="box_head round_top"></h2>
			<div class="block box_content round_bottom padding_20">
				<label class="control-label" for="focusedInput">Starting Bill number (last bill number + 1)</label>
				<div class="controls"><%= f.number_field :bill_number_start %></div>
				<label class="control-label" for="focusedInput">Total number of bills (number of units)</label>
				<div class="controls"><%= f.number_field :bill_number_end %></div>
				<label class="control-label" for="focusedInput">Bill number Identifier(Society initial)</label>
				<div class="controls"><%= f.text_field :bill_number_format %></div>
			<ul>
				<div class="controls">
					<label class="checkbox uniform">
					<%= f.check_box :locked_period %>
					<%= f.label :locked_period, "Bill Finalised?" %>
					</label>
				</div>
			</ul>
				<div class="form-actions">
					<%= f.submit 'Generate bills', :class => 'btn btn-primary'  %>
					<%= link_to 'Cancel', bill_headers_path, :class => 'btn' %>
				</div>
			</div>
		</div>
	</div><!--/span-->
</div><!--/row-->
<% end %>

app/views/bill_headers/edit.html.haml
%h1 Editing bill_header

= render 'form'

= link_to 'Show', @bill_header
\|
= link_to 'Back', bill_headers_path

app/views/bill_headers/index.html.erb
<div class="row-fluid">
  <div class="span12">
	<ul class="breadcrumb">
	<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
	<li class="active">Bill Header </li>
	<li class="pull-right"> </li>
	</ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"></h2>
			<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
			<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
			<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
			<div class="toggle_container">					
			<div class="block box_content round_bottom padding_20">
			<table class="table table-striped table-condensed table-bordered">
			<thead>
			  <tr>
				<th>Bill date</th>
				<th>From</th>
				<th>To</th>
				<th>Bill cycle</th>
				<th>Grace period</th>
				<th>Start Bill no</th>
				<th>End Bill no</th>
				<th>Bill format</th>
				<th>Final?</th>
				<th>Society</th>
				<th>Edit</th>
				<th>Cancel</th>
			  </tr>
			</thead>
			<tbody>
			<% @bill_headers.each do |bill_header| %>
			  <tr>
				<td><%= link_to h(l(bill_header.bill_date, :format => :long)), bill_header_url(bill_header) %></td>
				<td><%= l(bill_header.from_date, :format => :long) %></td>
				<td><%= l(bill_header.to_date, :format => :long) %></td>
				<td><%= bill_header.bill_cycle %></td>
				<td><%= bill_header.grace_period %></td>
				<td><%= bill_header.bill_number_start %></td>
				<td><%= bill_header.bill_number_end %></td>
				<td><%= bill_header.bill_number_format %></td>
				<td><%= bill_header.locked_period %></td>
				<td><%= bill_header.society_id %></td>
				<td><%= link_to ( image_tag("/assets/Overlay-edit.png")), edit_bill_header_path(bill_header), :class => 'btn' %></td>
				<td><%= link_to ( image_tag("/assets/Overlay-cancel.png")), bill_header, :confirm => 'Are you sure?', :method => :delete, :class => 'btn' %></td>
			  </tr>
			<% end %>
			</tbody>
			</table>
				<br>
				</br>
				<%= will_paginate @bill_headers %>
				<%= link_to 'New Bill header', new_bill_header_path ,:class => 'btn btn-link' %>
				</div>
			</div>
		</div>
	</div>
</div><!--/row--> 

app/views/bill_headers/new.html.erb
<%= render 'form' %>

app/views/bill_headers/show.html.erb
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
			<li><a href="http://localhost:3000/meetings">Bill Headers</a> <span class="divider">/</span></li>                                      
			<li class="active"><%= controller.action_name.capitalize %> </li>
		</ul>
	</div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="box grad_colour_dark_blue" id="box_0">
				<h2 class="box_head round_top">Bill Header</h2>
				<a href="#" class="settings box_button_3" title="config">&nbsp;</a>
				<a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
				<a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
				<div class="toggle_container">					
			<div class="block box_content round_bottom padding_20">
				<div class="block box_content round_bottom padding_20">
					<label class="control-label" for="focusedInput">Bill Date: <%= @bill_header.bill_date %></label>
					<label class="control-label" for="focusedInput">From <%= @bill_header.from_date %>&nbsp;
					To &nbsp; <%= @bill_header.to_date %></label>
					<label class="control-label" for="focusedInput">Bill Cycle : Every <%= @bill_header.bill_cycle %> months</label>
					<label class="control-label" for="focusedInput">Grace Period : <%= @bill_header.grace_period %> days</label>
					<label class="control-label" for="focusedInput">Starting Bill number: <%= @bill_header.bill_number_start %></label>
					<label class="control-label" for="focusedInput">Total number of bills : <%= @bill_header.bill_number_end %></label>
					<label class="control-label" for="focusedInput">Bill number Identifier: <%= @bill_header.bill_number_format %></label>
					<label class="control-label" for="focusedInput">Bill Finalised? : <%= @bill_header.locked_period %></label>
				</div>
			 	<div class="form-actions">
					<%= link_to ( image_tag("/assets/Overlay-edit.png")+' '+'Edit'), edit_bill_header_path(@bill_header), :class => 'btn' %>
					<%= link_to 'Back to Bill header', bill_headers_path, :class => 'btn' %>
				</div>
			</div>
		</div>
	</div>
	</div>
</div><!--/row--> 