config/routes.rb
RailsPrelaunchSignup::Application.routes.draw do

  resources :activities

  resource :calendar, :only => [:show]

  resources :events

#----- Prelaunch sign up------------------------
  authenticated :user do
    root :to => 'home#index'
  end
    root :to => 'home#index'

  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  match 'units/unit_update' => 'units#unit_update', :via => :get, :as => :unit_update

#------------Baseapp2----------------

    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email
        get :invite
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end

#------------Baseapp2------end----------
  resources   :after_register
#------------Dhtmlx grid----------------------
    resources :societies do
       match '/master',      :to => 'societies#view',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resource :unit_types do
       match '/unit_types',  :to => 'unit_types#show',  :requirements => { :method => :get }
        collection do
          get 'view'
          get 'data'
          get 'dbaction'
          get 'show'
        end
    end
    resources :members do
       match '/view_members',     :to => 'members#view',  :requirements => { :method => :get }
        collection do
          get 'data'
          get 'dbaction'
          get 'view'
          get 'index'
       end
    end

    resources :memberships do
      match '/memberships', :to => 'memberships#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
     end

   resources :units do
    match '/unit', :to => 'units#show', :requirements => { :method => :get }
      collection do
        get 'data'
        get 'dbaction'
        get 'show'
        get 'index'
      end
    end
            
     resources :bill_setups do
      match '/bill_setups',       :to => 'bill_setups#show',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
            get 'show'
          end
      end
     resources :bill_headers do
      match '/bill_headers',       :to => 'bill_headers#view',  :requirements => { :method => :get }
          collection do
            get 'view'
            get 'data'
            get 'dbaction'
          end
      end

     resources :bills do
      match '/view_bills',       :to => 'bills#view',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'view'
            get 'index'
          end
      end
     resources :vendors do
      match '/view_vendors',       :to => 'vendors#show',  :requirements => { :method => :get }
          collection do
            get 'data'
            get 'dbaction'
            get 'show'
            get 'index'
          end
      end
  
  resources :staffs
  resources :meetings 
  resources :meeting_types 

  match '/committee_members',  :to => 'committee_members#index'
  match '/staffs',      :to => 'staffs#index'
  match '/vendors',     :to => 'vendors#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action
  # tublar--------------------

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  match '/videos', :to =>  "videos#index"
#  get "/insert_search/:search_type/:search"     => "api#search"
#  get "/:username/playlist/:playlist_name.json" => "api#user_playlist"
#  get "/stats"                                => "stats#index"
#  get "/genres"                               => "videos#genres"
#  get "/genre/:artist_band"                   => "videos#index"
#  get "/just/:artist_band"                    => "videos#index"
#  get "/similar/:artist_band"                 => "videos#index"
#  get "/video/:video_id"                      => "videos#index"
  
#  get "/:username/playlists"                  => "playlists#index"
#  get "/:username/playlist/:playlist_name"    => "playlists#listen"
#  match "/playlist/create"                    => "playlists#create"
#  match "/playlist/add_video"                 => "playlists#add_video"
#  match "/playlist/delete_video"              => "playlists#delete_video"
#  match "/get_playlists_video_belongs_to"     => "playlists#get_playlists_video_belongs_to"
  
#  post "/check_banned"                        => "bannedVideos#check"
#  post "/ban_video"                           => "bannedVideos#ban_video"

  get "static_pages/help"
#  get "static_pages/about"
#  get "static_pages/contact"
  match '/help',    :to => 'static_pages#help'
#  match '/about',   :to => 'static_pages#about'
#  match '/contact', :to => 'static_pages#contact'


  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :vendor_name, :contact_name, :vendor_phone,:vendor_email,:service_type,:address,
  :is_recurring, :payee_name, :pan_number,  :section_code, :service_tax_rate, 
    :stax_reg_number, :vat_number, :avatar,:avatar_file_name, :avatar_content_type,
   :avatar_file_size, :avatar_updated_at, :society_id

   belongs_to :society


end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.json
  before_filter :authenticate_user!
  load_and_authorize_resource 

  def data
    if current_user.has_role? :super_admin
      @vendors = Vendor.all
    else
      @vendors = Vendor.where("society_id = ?", current_user.society_id)
    end
  end

  def dbaction
    #called for all db actions
    vendor_name     = params["c0"]
    contact_name    = params["c1"]
    vendor_phone    = params["c2"]
    vendor_email    = params["c3"]
    service_type    = params["c4"]
    payee_name      = params["c5"]
    address         = params["c6"]
    stax_reg_number = params["c7"]
    service_tax_rate = params["c8"]
    pan_number      = params["c9"]
    is_recurring    = params["c10"]
    vat_number      = params["c11"]
    section_code    = params["c12"]
    avatar_file_name = params["c13"]
    society_id      = params["c14"]
     
    @mode = params["!nativeeditor_status"]
                  
    @id = params["gr_id"]
    case @mode
      when "inserted"
        vendor = Vendor.new
        vendor.vendor_name = vendor_name
        vendor.contact_name = contact_name
        vendor.vendor_phone = vendor_phone
        vendor.vendor_email = vendor_email
        vendor.service_type = service_type
        vendor.stax_reg_number = stax_reg_number
        vendor.service_tax_rate = service_tax_rate
        vendor.pan_number = pan_number
        vendor.is_recurring = is_recurring
        vendor.vat_number = vat_number
        vendor.section_code = section_code
        vendor.payee_name = payee_name
        vendor.address = address
        vendor.avatar_file_name = avatar_file_name
        vendor.society_id = current_user.society_id
        
        vendor.save!
        params[:action] = "insert"
        track_activity vendor
        
        @tid = vendor.id
      when "deleted"
        vendor=Vendor.find(@id)
        vendor.destroy
        params[:action] = "delete"
        track_activity vendor
        
        @tid = @id
      when "updated"
        vendor=Vendor.find(@id)
        vendor.vendor_name = vendor_name
        vendor.contact_name = contact_name
        vendor.vendor_phone = vendor_phone
        vendor.vendor_email = vendor_email
        vendor.service_type = service_type
        vendor.stax_reg_number = stax_reg_number
        vendor.service_tax_rate = service_tax_rate
        vendor.pan_number = pan_number
        vendor.is_recurring = is_recurring
        vendor.vat_number = vat_number
        vendor.section_code = section_code
        vendor.payee_name = payee_name
        vendor.address = address
        vendor.avatar_file_name = avatar_file_name
        vendor.society_id = current_user.society_id

        vendor.save!
        params[:action] = "update"
        track_activity vendor
        
        @tid = @id
    end 
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  # GET /vendors/new.json
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb">
    <li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
    <li><a href="http://localhost:3000/meetings">Vendors</a> <span class="divider">/</span></li>                                      
	<li class="active"><%= controller.action_name.capitalize %> </li>
	<li class="pull-right"> 
	</li>
    </ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span7">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"><%= @vendor.vendor_name %> </h2>
			<div class="block box_content round_bottom padding_20">

<%= form_for @vendor do |f| %>
				<% if @vendor.errors.any? %>
					<div class="error_messages">
						<h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>
						<ul>
						<% @vendor.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
						</ul>
					</div>
				<% end %>
				<div class="well form-inline">
					<%= f.text_field :vendor_name, :style=>"width:30%;", :placeholder => 'Company Name' %>
					<%= f.text_field :contact_name, :style=>"width:30%;", :placeholder => 'Contact Person' %>
					<%= f.text_field :vendor_phone, :style=>"width:30%;", :placeholder => 'Phone' %>
				</div>
				<div class="well form-inline">
					<%= f.text_field :vendor_email, :style=>"width:25%;", :placeholder => 'Email' %> 
					<%= f.number_field :service_type, :style=>"width:25%;", :placeholder => 'Type of service' %> 
					<%= f.text_field :vat_number, :style=>"width:25%;", :placeholder => 'Vat Number' %> 
				</div>
			 	<div class="well form-inline">
					<%= f.text_field :stax_reg_number, :style=>"width:40%;", :placeholder => 'Service tax Number' %> 
					<%= f.text_field :pan_number, :style=>"width:40%;", :placeholder => 'Pan Number' %> 
				</div>
				<div class="well form-inline">
					<%= f.text_field :address, :style=>"width:45%;", :placeholder => 'Current Address' %> 
					<%= f.text_field :payee_name, :style=>"width:45%;", :placeholder => 'Payee Name' %> 
				</div>
				<div class="well form-inline">
					<%= f.text_field :section_code, :style=>"width:40%;", :placeholder => 'Section code' %> 
				</div>
			</div>
		</div>
	</div>
	<div class="span5">
		<div class="box grad_colour_dark_blue" id="box_0">
			<h2 class="box_head round_top"><%= controller.action_name.capitalize %> Photo</h2>
			<div class="block box_content round_bottom padding_20">

				<label class="control-label" for="focusedInput">is recurring?</label>
				<div class="controls"><%= f.check_box :is_recurring %></div>
			 	<div class="form-actions">
					<%= f.submit nil, :class => 'btn btn-primary' %>
					<%= link_to 'Cancel', vendors_path, :class => 'btn' %>
				</div>
	<% end %></form>
			</div>
		</div>
	</div>
</div>

app/views/vendors/edit.html.erb
<%= render 'form' %>

app/views/vendors/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb">
    <li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
	<li class="active">Vendors </li>
    </ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
	<div class="span12">
        <div class="box grad_colour_dark_blue" id="box_0">
            <h2 class="box_head round_top"></h2>
            <a href="#" class="settings box_button_3" title="config">&nbsp;</a>
            <a href="#" class="toggle box_button_2" title="toggle">&nbsp;</a>
            <a href="#" class="destroy box_button_1" title="close">&nbsp;</a>
            <div class="toggle_container">					
            <div class="block box_content round_bottom padding_20">

			<table class="table table-striped table-condensed table-bordered">
	        <thead>
			  <tr>
			    <th>Name</th>
			    <th>Contact name</th>
			    <th>Mobile</th>
			    <th>Email</th>
			    <th>Payee name</th>
			    <th>Service type</th>
			    <th>Society</th>
			    <th>
			    </th>
			    <th>
			    </th>
			    <th>
			    </th>
			  </tr>
	        </thead>
			<tbody>
			  <% @vendors.each do |vendor| %>
			    <tr>
					<td><%= link_to h(vendor.vendor_name), vendor_url(vendor) %></td>
					<td><%= best_in_place vendor,:contact_name %></td>
					<td><%= best_in_place vendor,:vendor_phone %></td>
					<td><%= best_in_place vendor,:vendor_email %></td>
					<td><%= best_in_place vendor,:payee_name, vendor %></td>
					<td><%= best_in_place vendor,:service_type %></td>
					<td><%= vendor.society_id %></td>
					<td><%= link_to 'Show', vendor %></td>
					<td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
					<td><%= link_to 'Destroy', vendor, :confirm => 'Are you sure?', :method => :delete %></td>
			    </tr>
			  <% end %>
			 </tbody>
			</table>
<br>
</br>
<%= will_paginate @vendors %>
<%= link_to 'New Vendor', new_vendor_path %>
                </div>                                
            </div>
        </div>
	</div>
</div><!--/row--> 

app/views/vendors/new.html.erb
<%= render 'form' %>

app/views/vendors/show.html.erb
		<%= render 'shared/dhtmlx_stylesheet' %>
    	<%= render 'shared/dhtmlx_javascript' %>
<div class="row-fluid">
  <div class="span12">
    <ul class="breadcrumb">
    <li><a href="http://localhost:3000">Dashboard</a> <span class="divider">/</span></li>                                      
	<li class="active">Vendors </li>
    	<%= render 'shared/buttons' %>
    </ul>
  </div><!--/span-->
</div>

<div class="row-fluid">
  <div class="span12">
    <div id="recinfoArea"></div>
    <div id="grid_vendor" style="margin-top: -10px; width:100%; height:425px; background-color:white;overflow:hidden"></div>
    <div id="pagingArea"></div>

	<script type="text/javascript" charset="utf-8">
	function add_r() {
    var ind1 = "New Vendor";
    var ind2 = "";
    var ind3 = '';
    var ind4 = "";
    var ind5 = "";
    var ind6 = "";
    var ind7 = "";
    var ind8 = "";
    var ind9 = "";
    var ind10 = "";
    var ind11 = "";
    var ind12 = "";
    
    grid.addRow(grid.uid(), [ind1, ind2, ind3, ind4, ind5, ind6, ind7, ind8, ind9, ind10, ind11, ind12], 0);
	}
		var grid = new dhtmlXGridObject("grid_vendor");
		grid.setImagePath("imgs/");
		grid.setHeader("Company Name, Contact name, phone, Email,Service Type, Payee name, Address, S.Tax reg.no,S.tax rate, Pan number, Is recurring?, Vat number, Section code, Photo, S Id");
		grid.attachHeader("#text_filter,#text_filter,#text_filter,#text_filter,#select_filter,#text_filter");
		grid.setColSorting("str,str,str,str,str,str,str,str,str,str,str,str,str,str,int");
		grid.setInitWidths("150,100,80,140,100,140,160,70,70,60,60,60,100,60,50");
		grid.setColAlign("left,left,left,left,left,left,left,left,right,left,center,left,left,right,center");
		grid.setColTypes("ed,ed,ed,ed,ed,ed,txt,ed,ed,ed,acheck,ed,ed,img,ed");
		grid.enableMultiselect(true);
		grid.enableValidation(true);
		grid.setSkin("sbdark");
		grid.enablePaging(true, 18, 25, "pagingArea", true, "recinfoArea");
		grid.setPagingSkin("bricks");
		grid.init();
		grid.load("vendors/data.xml");
		
		dp = new dataProcessor("vendors/dbaction.xml/");
		dp.init(grid);

		//link dataprocessor to the grid;
		function clear_filter(){
			grid.filterBy(0,"");
			grid._f_rowsBuffer = null;
		}
		function add(){
			clear_filter();
			grid.addRow(grid.uid(), 'vendor');
		}
		function remove(){
			clear_filter();
			grid.deleteSelectedRows();
		}
	</script>
  </div>
</div>